/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkyMark' at '5/7/16 1:28 PM' with Gradle 2.13
 *
 * @author MarkyMark, @date 5/7/16 1:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
